# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

# config file for development.


## => Site Settings
##############################
text_color_theme: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
url: # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: # does not include hostname
title: Someone's blog
description: > # this means to ignore newlines until "Language & timezone"
  Someone's Blog


## => Language and Timezone
##############################
lang: # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  name: Someone
  email: someone@somemail.com # your Email address e.g. someone@site.com
  facebook: someone # your Facebook username
  twitter: someone # your Twitter username
  github: someone # your GitHub username
  linkedin: # your Linkedin username
  googleplus: # your Google+ username
  weibo: # your Weibo username
  douban: # your Douban username


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: someone/someone.github.io
repository_tree: master


## => Navigation
##############################
paths:
  base: /
  home: /
  all:  /all.html
  rss:  /feed.xml

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html
  - title: Jekyll
    url: https://jekyllrb.com/


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## Markdown Enhancements

# Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true

# Mermaid
mermaid: true # false (default), true

# Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 3
paginate_path: /blog/page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Comments
##############################
## Disqus
disqus:
  shortname: # the Disqus shortname for the site

## Gitalk
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID: 143666b578a416f82175 # GitHub Application Client ID
  clientSecret: 1d1c0604a1a4bff9b59ab7f56724dc0e8b837775 # GitHub Application Client Secret
  repository: gitalk-demo # GitHub repo
  owner: kitian616 # GitHub repo owner
  admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
    - kitian616


## => Pageview
##############################
## Leancloud
leancloud:
  app_id: # LeanCloud App id
  app_key: # LeanCloud App key
  app_class: # LeanCloud App class


## => Analytics
##############################
## Google Analytics
ga_tracking_id: # Google Analytics id for the site


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  # - /test
  - /vendor


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji